#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/types.h>
#include <errno.h>
#include <string.h>
#include <netinet/in.h>
#include <sys/mman.h>
#include <dlfcn.h>
#include <sys/socket.h>
#include <linux/if_packet.h>
#include <net/ethernet.h>
#include <arpa/inet.h>
#include <error.h>
#include <dlfcn.h>
#include <rpc/rpc.h>
#include <linux/if.h>
#include <sys/ioctl.h>

#include "exlay.h"
#include "protocol.h"
#include "daemon.h"
#include "exlay_rpc.h" /* automatically generated by rpcgen */

#define LIBPREFIX "/home/vagrant/work/exlay/poc/protocols/lib/lib"
#define LIBSUFFFIX ".so"

extern void exlayprog_1(struct svc_req *rqstp, register SVCXPRT *transp);
static struct sockaddr_ll daem_addr_ll;
static int daem_sock;
static socklen_t sk_len = sizeof(struct sockaddr_ll);
static int prot_ctr = 0;
static int list_len = 0;
static struct sockaddr_in cli_addr_in;
static unsigned char exsock = 0;

struct proto_info prinfo_head;
struct binding_tree root;

static char *pwd;

struct exlay_ep ep_head = {
	.fp = &ep_head,
	.bp = &ep_head,
};

static char *get_libpath(char *proto)
{
	char *ret = NULL;
	struct proto_info *p;
	for (p = prinfo_head.fp; p != &prinfo_head; p = p->fp) {
		if (strcmp(proto, p->name) == 0) {
			/* found */
			ret = p->path;
			break;
		}
	}
}

static void reflect_to_binding_tree(struct exlay_ep *exep)
{

}
static int init_exlay(void)
{
	root.upper = &root;
	root.lower = NULL;
	root.fp = &root;
}



static struct exlay_ep *get_ep_from_sock(int sock)
{
	struct exlay_ep *p;
	for (p = ep_head.fp; p != &ep_head; p = p->fp) {
		if (sock == p->ep) {
			/* found */
			return p;
		}
	}
	/* if not found */
	return NULL;
}

static void init_stack(struct exlay_ep *ep, int nr_layers)
{
	int i;
	ep->nr_layers = nr_layers;
	for (i = 0; i < nr_layers; i++) {
		ep->btm[i].layer = i + 1;
		ep->btm[i].proto = NULL;
		ep->btm[i].lbind = NULL;
		ep->btm[i].rbind = NULL;
		ep->btm[i].upper = NULL;
	}
}


static void func_daem_add(void *buf, int len)
{
}

static void func_daem_info(void *buf, int len)
{
	debug_printf("cmd = info\n");
	/*
	 * XXX: PENDING
	 * */
}
static void func_daem_del(void *buf, int len)
{
}
static void func_daem_update(void *buf, int len)
{
	debug_printf("cmd = update\n");
	struct exlay_hdr *hdr = (struct exlay_hdr *)buf;
	uint8_t *data = (uint8_t *)buf + EXLAYHDRSIZE;
	char prot_name[MAXPROTNAMELEN] = {0};
	char prot_path[MAXPROTPATHLEN] = {0};
	memcpy(prot_name, data, hdr->len_proto_name);
	memcpy(prot_path, data + hdr->len_proto_name, hdr->len_proto_path);
	int ret;

	if (hdr->code != CODE_REQ) {
		/* invalid request pkt */
		hdr->code = CODE_INVREQ;
		memset(data, 0, len - EXLAYHDRSIZE);
		/* XXX error message should be written */
		goto OUT;
	} 

	struct proto_info *prt;
	/* whether the protocol name to be added has already exist or not */
	for (prt = prinfo_head.fp; prt != &prinfo_head; prt = prt->fp) {
		if (strcmp(prt->name, prot_name) == 0) {
			/* found */
			break;
		}
	}

	if (prt == &prinfo_head) {
		hdr->code = CODE_NEXIST;
		goto OUT;
	}

	memcpy(prt->path, prot_path, hdr->len_proto_path);
	debug_printf("prot %s (%s) was successfully updated\n", 
			prt->name, prt->path);

	hdr->code = CODE_OK;

OUT:
	ret = sendto(daem_sock, buf, EXLAYHDRSIZE + strlen((char *)data), 0, 
			(struct sockaddr *)&cli_addr_in, sk_len);

	if (ret < 0) {
		perror("sendto");
	}
	return;
}


struct daem_cmd {
	uint8_t cmd;
	void (*cmd_func)(void *buf, int len);
} daem_cmd_table[NR_DAEM_CMDS + 1] = {
	{CMD_ADD,     func_daem_add},
	{CMD_INFO,    func_daem_info},
	{CMD_DEL,     func_daem_del},
	{CMD_UPDATE,  func_daem_update},
	{CMD_UNKNOWN, NULL}
};


int init_daemon(char *ifname)
{
	struct ifreq if_req;
	
	if ((daem_sock = socket(AF_PACKET, SOCK_RAW, htons(ETH_P_ALL))) < 0) {
		perror("socket");
		return errno;
	}

	memset(&daem_addr_ll, 0, sizeof(struct sockaddr_ll));
	strncpy(if_req.ifr_name, ifname, strlen(ifname));

	if (ioctl(daem_sock, SIOCGIFINDEX, &if_req) < 0) {
		perror("ioctl");
		close(daem_sock);
		return errno;
	}
	daem_addr_ll.sll_family = PF_PACKET;
	daem_addr_ll.sll_protocol = htons(ETH_P_ALL);
	daem_addr_ll.sll_ifindex = if_req.ifr_ifindex; 

	if (bind(daem_sock, (struct sockaddr *)&daem_addr_ll, sizeof(struct sockaddr_ll)) < 0) {
		perror("bind");
		return errno;
	}

	if (ioctl(daem_sock, SIOCGIFFLAGS, &if_req) < 0) {
		perror("ioctl");
		close(daem_sock);
		return errno;
	}
	
	if_req.ifr_flags = if_req.ifr_flags|IFF_PROMISC|IFF_UP;
	if (ioctl(daem_sock, SIOCSIFFLAGS, &if_req) < 0) {
		perror("ioctl");
		close(daem_sock);
		return errno;
	}

	prinfo_head.fp = &prinfo_head;

	return 0;
}

int main(int argc, char **argv, char **env)
{
	int ret;
	uint8_t buf[MAXPKTSIZE] = {0};
	if (argc != 2) {
		fprintf(stderr, "usage: exlay_daemon <ifname>\n");
		return EXIT_FAILURE;
	}

	if (init_daemon(argv[1]) != 0) {
		return EXIT_FAILURE;
	}
	init_exlay();
	debug_printf("init_daemon: finish...\n");

	register SVCXPRT *transp;

	pmap_unset(EXLAYPROG, EXLAYVERS); 
	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, EXLAYPROG, EXLAYVERS, exlayprog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (EXLAYPROG, EXLAYVERS, udp).");
		exit(1);
	}

	svc_run();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	return 0;
}

/* RPC svc */

int *ex_create_stack_1_svc(unsigned int nr_layers, struct svc_req *rqstp)
{
	static int result;
	struct exlay_ep *exep;
	exep = (struct exlay_ep *)malloc(sizeof(struct exlay_ep));
	exep->nr_layers = nr_layers;
	exep->ep = ++exsock;
	exep->btm = (struct exlay_layer *)malloc(sizeof(struct exlay_layer) * nr_layers);
	exep->top = &exep->btm[nr_layers - 1];
	init_stack(exep, nr_layers);

	INSERT_TO_LIST_HEAD(&ep_head, exep);
	//return exep->sock;
	result = exep->ep;
	return &result;
}

int *ex_set_binding_1_svc(
		int exsock, 
		unsigned int lyr, 
		char *proto, 
		binding lbind, 
		unsigned int bsize, 
		int upper, 
		struct svc_req *rqstp)
{
	static int result = 0;

	struct exlay_ep *exep;
	char *buf;

	exep = get_ep_from_sock(exsock);
	if (exep == NULL) {
		/* no such exlay endpoint */
		result = -1;
		goto OUT;
	}
	if (exep->nr_layers > lyr || lyr == 0) {
		/* no such layer in the endpoint */
		result = -1;
		goto OUT;
	}
	/* XXX if ex_set_binding is already called before, notify */

	buf = get_libpath(proto);
	if (buf == NULL) {
		/* cannot found protocol library */
		result = -1;
		goto OUT;
	}

	/* load library of "proto" by protobj symbol */
	void *handle = dlopen(buf, RTLD_NOW|RTLD_GLOBAL);
	char *err;
	if ((err = dlerror()) != NULL) {
		fputs(err, stderr);
		putchar('\n');
		result = -1;
		goto OUT;
	}
	/* XXX how should it specify the symbol name of protobj? */
	exep->btm[lyr-1].proto = (struct protobj *)dlsym(handle, proto);
	if ((err = dlerror()) != NULL) {
		fputs(err, stderr);
		putchar('\n');
		result = -1;
		goto OUT;
	}

	/* set requested binding */
	uint8_t size = exep->btm[lyr-1].proto->bind_size;
	uint8_t uplyr_type_s = exep->btm[lyr-1].proto->upper_type_size;
	exep->btm[lyr-1].lbind = malloc(size);
	memcpy(exep->btm[lyr-1].lbind, lbind.binding_val, size);

	if (upper != 0) {
		exep->btm[lyr-1].upper = malloc(uplyr_type_s);
		memcpy(exep->btm[lyr-1].upper, &upper, uplyr_type_s);
	} else {
		exep->btm[lyr-1].upper = NULL;
	}

OUT:
	return &result;

}

int *ex_bind_stack_1_svc(int ep, struct svc_req *rqstp)
{
	static int result = 0;
	struct exlay_ep *exep;
	exep = get_ep_from_sock(ep);
	if (exep == NULL) {
		/* no such endpoint */
		result = -1;
		goto OUT;
	}
	/* reflect stack to binding_tree */
	reflect_to_binding_tree(exep);

OUT:
	return &result;
}
int *ex_set_remote_1_svc(
		int ep, 
		int lyr, 
		binding rb, 
		unsigned int bsize, 
		struct svc_req *rqstp)
{
	static int result = 0;

	struct exlay_ep *exep;
	exep = get_ep_from_sock(ep);
	if (exep == NULL) {
		/* no such endpoint */
		result = -1;
		goto OUT;
	}
	uint8_t size = exep->btm[lyr-1].proto->bind_size;
	if (rb.binding_val == NULL) {
		/* unreachable */
		goto OUT;
	} else {
		if (exep->btm[lyr-1].rbind == NULL) {
		/* ex_set_remote is called for the first time */
			if ((exep->btm[lyr-1].rbind = malloc(size)) == NULL) {
				fprintf(stderr, "ex_set_remote: malloc: error: %d\n", errno);
				result = errno;
				goto OUT;
			}
		}
		memcpy(exep->btm[lyr-1].rbind, rb.binding_val, size);
	}

OUT:
	return &result;
}
int *ex_dial_stack_1_svc(int ep, struct svc_req *rqstp)
{
	static int result;
	return &result;
}

int *ex_listen_stack_1_svc(int ep, struct svc_req *rqstp)
{
	static int result;
	return &result;
}
int *ex_close_stack_1_svc(int ep, struct svc_req *rqstp)
{
	static int result = 0;
	struct exlay_ep *p;
	p = get_ep_from_sock(ep);
	if (p == NULL) {
		/* no such exlay endpoint */
		result = -1;
		goto OUT;
	}
	REMOVE_FROM_LIST(p);
	free(p);

OUT:
	return &result;
}

char **exlay_list_1_svc(struct svc_req *rqstp)
{
	static char *result = "";
	debug_printf("cmd = list\n");
	static char is_freeable = 0;

	if (is_freeable) {
		free(result);
		result = "";
		is_freeable = 0;
	}

	if (list_len > 0) {
		char *p;
		result = malloc(list_len);
		is_freeable = 1;
		memset(result, '\0', list_len);

		struct proto_info *prt;
		for (prt = prinfo_head.fp, p = result; prt != &prinfo_head; prt = prt->fp) {
			memcpy(p, prt->name, strlen(prt->name));
			p += (strlen(prt->name));
			*p++ = '\n';
		}
		*p = '\0';
	} 
OUT:
	return &result;
}

int *exlay_add_1_svc(char *proto, struct svc_req *rqstp)
{
	static int result = 0;
	debug_printf("cmd = add\n");
	if (result) {
		result = 0;
	}

	struct proto_info *prt;
	/* whether the protocol name to be added has already exist or not */
	for (prt = prinfo_head.fp; prt != &prinfo_head; prt = prt->fp) {
		if (strcmp(prt->name, proto) == 0) {
			result = CODE_DUP;
			goto OUT;
		}
	}
	struct proto_info *new_prt;
	new_prt = (struct proto_info *)malloc(sizeof(struct proto_info));
	if (new_prt == NULL) {
		result = CODE_NMEM;
		goto OUT;
	}
	new_prt->path = (char *)malloc(sizeof(char) * strlen(proto) + strlen(LIBPREFIX) + strlen(LIBSUFFFIX));
	new_prt->name = (char *)malloc(sizeof(char) * strlen(proto));
	memcpy(new_prt->name, proto, strlen(proto));
	//memcpy(new_prt->path, path, strlen(path));
	new_prt->name[strlen(proto)] = '\0';
	//new_prt->path[strlen(path)] = '\0';
	prot_ctr++;
	list_len += (strlen(proto) + 1);
	sprintf(new_prt->path, "%s%s%s", LIBPREFIX, proto, LIBSUFFFIX);

	void *handle = dlopen(new_prt->path, RTLD_LAZY|RTLD_GLOBAL);
	char *err;
	if ((err = dlerror()) != NULL) {
		fputs(err, stderr);
		putchar('\n');
		result = CODE_NFND;
		goto OUT;
	}
	INSERT_TO_LIST_HEAD(&prinfo_head, new_prt);
	debug_printf("prot %s (%s) was successfully added\n", 
			new_prt->name, new_prt->path);

OUT:
	return &result;
}

int *exlay_del_1_svc(char *proto, struct svc_req *rqstp)
{
	static int result = 0;
	debug_printf("cmd = del\n");

	struct proto_info *prt;
	/* whether the protocol name to be deleted has really exist or not */
	for (prt = prinfo_head.fp; prt != &prinfo_head; prt = prt->fp) {
		if (strcmp(prt->name, proto) == 0) {
			/* found */
			break;
		}
	}

	if (prt == &prinfo_head) {
		result = CODE_NEXIST;
		goto OUT;
	}

	REMOVE_FROM_LIST(prt);
	prot_ctr--;
	list_len -= (strlen(prt->name) + 1);
	debug_printf("prot %s (%s) was successfully removed\n", 
			prt->name, prt->path);
	free(prt);

OUT:
	return &result;
}

char **exlay_info_1_svc(char *proto, struct svc_req *rqstp)
{
	static char **result;
	return result;
}

int *exlay_update_1_svc(char *proto, char *new_path, struct svc_req *rqstp)
{
	static int result = 0;
	return &result;
}
